### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by okdistribute** [simplysecure/dots-patterns#26]
## Topic

Every pattern will have only 1 category. This is a first draft of the current patterns we have and some proposed categorization of them. Feedback welcome!

## Discussion

These 4 categories came from what @bumbleblue shared in our meeting two weeks ago. I took our current patterns and looked at the patterns workshop we did, and then categorized them based on what seems to make most sense.

Open questions:
1. Do these categories make sense? Do we need to add, remove, or change any?
1. Do any of these patterns seem miscategorized?
1. How should categories be formatted in the markdown?

## Categories

identity (& agency?)
- full address
- disposable identity
- persistent identity
- host roulette
- @ means membership

sharing (& permissions?)
- QR code verification
- paper keys
- visual hash
- standards marker
- sharing is caring
- whisper links

sync (& status?)
- network health indicator
- age indicator
- discovery pub
- physical beacon
- protocol agnosticism

moderation (& curation?)
- tombstones
- cautious optimism
- social radius slider
- content curators
- time machine
- village or city

**Comment by bumbleblue** [comment]
another iteration!

**Comment by cafca** [comment]
My current plan is this: categories will get their own folder adjacent to patterns. Inside there is one file per category. 

The front matter of pattern files then specifies its category as a "tag". You can have a look [here](https://github.com/simplysecure/dots-patterns/blob/c6b9edcdfad766f187b0fd37e6ae3d76c2122b70/patterns/QR-code-verification.md). Maybe there will be a special tag-syntax for categories, e.g. `category/moderation-curation` or something like that.

**Comment by okdistribute** [comment]
sounds good @cafca thanks!

**Comment by okdistribute** [comment]
@bumbleblue added inline question about category names to simplify them

**Comment by milo-trujillo** [comment]
Maybe a fifth category for content discovery? The biggest area I think dots-patterns can grow in is how to find users and data that are relevant to them. Things that might go in this category include:

* Bootstrapping (how to join a p2p system, direct peer identifiers or Cabal-style group invites)
* Pubs (Scuttlebutt-style groups, public instances of SSB, CWTCH, Mastadon)
* Trackers (central-but-redundant servers for decentralized content, like torrents)
* Suggested peers (simple friends-of-friends suggestions, or leveraging "who's mirroring content I'm interested in" from `network health indicators` to find peers)

There are tie-ins with patterns from several other categories, like using `QR code verification` for easy-to-share group or peering invite codes, using the hosts from `discovery pub` to find more peers, or something akin to `social radius slider` to indicate what level of contact information you're comfortable having your peers share with others to help make introductions. Nevertheless, I think this category is distinct, and these patterns shouldn't be folded into the existing four categories.

**Comment by okdistribute** [comment]
@milo-trujillo I agree!

Unfortunately, only one of the patterns you list (pubs) has already been written. I'm hesitant to create a category if we haven't made the patterns yet. 

Proposal: we write two new patterns, bootstrapping & trackers. Then, we will have at least 3 patterns (including Pub) for the 'discovery' category. 

What do you think @bumbleblue?

@milo-trujillo would you be interested in helping me get these two patterns out the door?

**Comment by milo-trujillo** [comment]
Yes, I agree that the patterns should come before/with the new category. I'd be happy to help work on bootstrapping and trackers. I wrote about [torrents/torrent-trackers recently](https://backdrifting.net/post/037_torrents), so those ideas are fresh and quick to recycle.

**Comment by okdistribute** [comment]
The last bit of work we have here is to write descriptions for each category!
