### ISSUE TITLE
Discovery Pub

### ISSUE THREAD

**Issue by okdistribute** [simplysecure/dots-patterns#4]
https://github.com/simplysecure/dots-patterns/blob/master/patterns/discovery-pub.md

**Comment by bumbleblue** [comment]
I'm having trouble understanding what this pattern is. There seem to be 4 recommendations related to search:

1. Allow people to choose local vs global (vs ...) search scope.
2. Provide default blocklists.
3. Be transparent about algorithm usage.
4. Think about (?) whether you want fat/thin/gossipy searches.

I think 1 and 4 are relevant here, 2 + 3 are other considerations? Maybe 2 is even its own pattern.

**Comment by bumbleblue** [comment]
Made some changes. Also wondering why this is called Discovery Pub? Shall we explain? Or rename?

**Comment by okdistribute** [comment]
Thanks for the changes, looks better~!

Yeah maybe 2 is it's own pattern. Discovery Pub is just a name that came out of our workshop, SSB calls it a "pub" so that's where that came from, but I'm open to other ideas. I'd be happy to make it more our own or come up with a more generic name...

Spitballing here a bit.. in some ways it's more like a federated server than component in a peer-to-peer application. What makes it different than a simple federated server? If there isn't much difference, should we just call it that?
