### ISSUE TITLE
Adding images to the pattern examples

### ISSUE THREAD

**Issue by okdistribute** [simplysecure/dots-patterns#42]
Are there any considerations to think about for formatting or otherwise for how we add images to the patterns? 

I think it might be useful to add images to the examples section, i.e., a screenshot of the pattern's use in the wild in some other application. Thoughts?
@cafca @kirakirawes

**Comment by okdistribute** [comment]
I did a quick exploration of what kind of example images we could pull (that aren't logos) here:
https://miro.com/app/board/o9J_lXyQ2fk=/

**Comment by cafca** [comment]
I think this should be solved per #52 @okdistribute 

However, I noticed there are still a couple of patterns with missing or malformed examples sections.
