### ISSUE TITLE
User Identity

### ISSUE THREAD

**Issue by okdistribute** [simplysecure/dots-patterns#6]
https://github.com/simplysecure/dots-patterns/blob/master/patterns/user-identity.md

**Comment by mrchrisadams** [comment]
Thanks for getting this together. I was really happy to find this, as I've been looking for some useful ideas and patterns beyond the Tripartite Identity Pattern from Yahoo in 2008 to help me think this through on projects.

I'm sharing them here in case they're a useful reference.

http://habitatchronicles.com/2008/10/the-tripartite-identity-pattern/
https://www.b-list.org/weblog/2018/feb/11/usernames/

**Comment by okdistribute** [comment]
Thanks @mrchrisadams for the links! Totally useful.  Related recent proposal from matrix folks regarding updating their userids to use a public key instead so that the domain is not immutably written into the DAG: https://github.com/matrix-org/matrix-doc/blob/rav/proposal/remove_mxids_from_events/proposals/1228-removing-mxids-from-events.md

**Comment by link2xt** [comment]
Relevant example is Zot nomadic identity: https://zotlabs.org/page/zot/specs+zot6+nomadic+identity
