### ISSUE TITLE
Link to the published library at decentpatterns.xyz/library/

### ISSUE THREAD

**Issue by mrchrisadams** [simplysecure/dots-patterns#68]
Hi there!

I came across this via github, and it took me a while to find  the link to the main site.

Would you accept a PR like this adding a link to the published library?

https://github.com/simplysecure/dots-patterns/pull/69

_(my earlier PR was linking to the wrong repo. #69 should be easier to merge in)_

**Comment by okdistribute** [comment]
Yes thank you for the suggestion!
